# Site settings
title: "[kumo.it]"
email: kumo@kumo.it
description: 'A collection of random thoughts, together with a dusty pile of BeOS software and Ruby on Rails notes. Made by <a href="https://twitter.com/kumo" target="_blank">@kumo</a>.'
url: "http://www.kumo.it"
baseurl: ""

author:
  name: 'Rob Clarke'
  username: kumo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/

paginate: 5
#paginate_path: "page/:num/"

# Tracking settings

gauges: 537626b98bfdf7060a000c47
google: UA-84351-1

github:
  repo:  https://github.com/kumo

gems:
- jekyll-redirect-from
- jekyll-sitemap
