# Site settings
title: kumo.it
email: kumo@kumo.it
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://kumo.it"
username: kumo

# Build settings
markdown: kramdown
permalink: pretty

# Twitter settings

gauges: 537626b98bfdf7060a000c47
google: UA-84351-1
