# Site settings
title: "[kumo.it]"
email: kumo@kumo.it
description: 'Random stuff from an ex-BeOS developer. Made by <a href="https://twitter.com/kumo" target="_blank">@kumo</a>.'
url: "http://www.kumo.it"
baseurl: ""

author:
  name: 'Rob Clarke'
  username: kumo

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty

paginate: 5

# Tracking settings

gauges: 537626b98bfdf7060a000c47
google: UA-84351-1

github:
  repo:  https://github.com/kumo
